name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        USER: ${{ secrets.Username }}
        PASS: ${{ secrets.Pass }}
      run: |
        echo $USER
        echo $PASS
        docker build . --file Dockerfile --tag nileshgulve/github:latest
        docker login -u $USER -p $PASS
        
        docker push nileshgulve/github:latest
